version: "3.9"

volumes:
  PGDATA:
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
    - PGDATA:/var/lib/postgresql/data_chat/pgdata
